### ISSUE TITLE
Cf Industries and CDW

### ISSUE THREAD

**Issue by tymur999** [wbail/awesome-csharp-jobs#1]
CF Industries and CDW, both USA, are companies that uses c#

**Comment by wbail** [comment]
Could you please open a pull request with the companies website?

**Comment by tymur999** [comment]
@wbail 
Hi, sorry, but I do not know the companies' websites. I believe it is only a section of the company that use C#, so not their general website. I'm sorry about that

**Comment by wbail** [comment]
@tymur999 Np, I tried to find the careers section on their websites and via LinkedIn, and I didn't found any job for developers. Thanks anyway!
